# Generated by Django 6.0.6 on 2026-06-15 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(default='소속 미상', max_length=100, verbose_name='소속')),
                ('start_time', models.DateTimeField(verbose_name='시작 일시')),
                ('end_time', models.DateTimeField(verbose_name='종료 일시')),
                ('sample_name', models.CharField(max_length=200, verbose_name='샘플명')),
                ('sample_details', models.TextField(blank=True, verbose_name='샘플 세부 정보')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인')], default='PENDING', max_length=10)),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='장비 점검(예약 차단)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
            ],
        ),
    ]
