# Generated by Django 6.0.6 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_issuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
