# Generated by Django 6.0.6 on 2026-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='reservations/attachments/'),
        ),
    ]
