# Generated by Django 6.0.6 on 2026-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_notice_equipment_hourly_rate_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='전체 사이트 점검 모드 (접속 차단)')),
                ('block_reservations', models.BooleanField(default=False, verbose_name='신규 예약 막아두기 (달력 조회는 가능)')),
                ('maintenance_message', models.CharField(default='현재 시스템 정기 점검 중입니다. 이용에 불편을 드려 죄송합니다.', max_length=200, verbose_name='점검 안내 문구')),
            ],
            options={
                'verbose_name': '시스템 제어판',
                'verbose_name_plural': '시스템 제어판',
            },
        ),
    ]
