# Generated by Django 6.0.6 on 2026-06-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='📌 상단 고정'),
        ),
    ]
