# Generated by Django 6.0.6 on 2026-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_notice_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='advisor_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='지도교수 교원 번호'),
        ),
    ]
