# Generated by Django 6.0.6 on 2026-06-18 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_userprofile_advisor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='점검 시작 일시')),
                ('end_time', models.DateTimeField(verbose_name='점검 종료 일시')),
                ('reason', models.CharField(default='정기 점검 및 수리', max_length=200, verbose_name='점검 사유')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.equipment', verbose_name='장비')),
            ],
        ),
    ]
