# Generated by Django 6.0.6 on 2026-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_equipmentmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
    ]
