# Generated by Django 6.0.6 on 2026-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_userprofile_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('INTERNAL', '내부 이용자 (동국대)'), ('EXTERNAL', '외부 이용자')], default='EXTERNAL', max_length=20, verbose_name='이용자 구분'),
        ),
    ]
