# Generated by Django 6.0.6 on 2026-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='advisor_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certified_equipment',
            field=models.ManyToManyField(blank=True, to='reservations.equipment', verbose_name='직접 사용 가능 장비'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='개인 학번/사번'),
        ),
    ]
