# Generated by Django 6.0.6 on 2026-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_userprofile_advisor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='equipment',
            name='external_hourly_rate',
            field=models.IntegerField(default=0, verbose_name='외부 시간당 요금(원)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_hourly_rate',
            field=models.IntegerField(default=0, verbose_name='내부 시간당 요금(원)'),
        ),
    ]
