# Generated by Django 6.0.6 on 2026-06-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_equipment_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='장비 약어 (달력 표시용)'),
        ),
    ]
